import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * FizzBuzz is a simple Java Swing application that determines whether a given number
 * is divisible by 3, 5, both, or neither, and displays the corresponding result.
 *
 * @author Nkechi Chukwuma
 * Last Edited: 20/04/2024
 */
public class FizzBuzz extends JFrame implements ActionListener {

    private JTextField val;
    private JButton button;
    private JLabel result;

    /**
     * Constructs a FizzBuzz object, initializes the GUI components,
     * and sets up the layout.
     */
    public FizzBuzz() {

        val = new JTextField();
        val.setBounds(50, 50, 150, 20);

        button = new JButton("Submit");
        button.setBounds(50, 200, 100, 50);
        button.addActionListener(this);

        result = new JLabel("Result");
        result.setBounds(50, 150, 200, 50);

        setTitle("FizzBuzz");
        setSize(300, 300);
        setLayout(null);
        setVisible(true);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);

        add(val);
        add(button);
        add(result);
    }

    /**
     * Determines whether the given value is divisible by 3, 5, both, or neither,
     * and updates the result label accordingly.
     * @param value The integer value to be checked.
     */
    public void funcFizzBuzz(int value) {
        String res;
        if (((value % 3) == 0) && ((value % 5) == 0)) {
            res = "FizzBuzz";
        } else if ((value % 3) == 0) {
            res = "Fizz";
        } else if ((value % 5) == 0) {
            res = "Buzz";
        } else {
            res = "Cannot Compute";
        }
        result.setText(res);
    }

    /**
     * Handles the action performed when the button is clicked.
     * Converts the text in the text field to an integer, then calls funcFizzBuzz.
     * Displays an error message if the input is not a valid integer.
     * @param e The ActionEvent generated by the button click.
     */
    public void actionPerformed(ActionEvent e) {
        try {
            String s = val.getText();
            int v = Integer.parseInt(s);
            if (e.getSource() == button) {
                funcFizzBuzz(v);
            }
        } catch (NumberFormatException ex) {
            result.setText("Please enter a valid integer.");
        }
    }

    /**
     * Main method to create and run the FizzBuzz application.
     * @param args The command line arguments (not used).
     */
    public static void main(String[] args) {
        SwingUtilities.invokeLater(FizzBuzz::new);
    }
}
